#include "platform/windows/WinCommon.h"
#include "app/TrayIcon.h"
#include "AudioslaveAssets.h"
#include "common/Branding.h"
#include "common/Strings.h"

#include <commctrl.h>
#include <shellapi.h>

namespace audioslave
{
namespace
{
struct Frame
{
    int size;
    const char* normal;
    int normalSize;
    const char* paused;
    int pausedSize;
};

// One frame per shell icon size (16 px at 100 % DPI ... 64 px at 400 %),
// generated by tools/make_icons.py, so the tray never shows a scaled icon.
const Frame frames[] = {
    { 16, AudioslaveAssets::normal16_png, AudioslaveAssets::normal16_pngSize, AudioslaveAssets::paused16_png, AudioslaveAssets::paused16_pngSize },
    { 20, AudioslaveAssets::normal20_png, AudioslaveAssets::normal20_pngSize, AudioslaveAssets::paused20_png, AudioslaveAssets::paused20_pngSize },
    { 24, AudioslaveAssets::normal24_png, AudioslaveAssets::normal24_pngSize, AudioslaveAssets::paused24_png, AudioslaveAssets::paused24_pngSize },
    { 28, AudioslaveAssets::normal28_png, AudioslaveAssets::normal28_pngSize, AudioslaveAssets::paused28_png, AudioslaveAssets::paused28_pngSize },
    { 32, AudioslaveAssets::normal32_png, AudioslaveAssets::normal32_pngSize, AudioslaveAssets::paused32_png, AudioslaveAssets::paused32_pngSize },
    { 36, AudioslaveAssets::normal36_png, AudioslaveAssets::normal36_pngSize, AudioslaveAssets::paused36_png, AudioslaveAssets::paused36_pngSize },
    { 40, AudioslaveAssets::normal40_png, AudioslaveAssets::normal40_pngSize, AudioslaveAssets::paused40_png, AudioslaveAssets::paused40_pngSize },
    { 48, AudioslaveAssets::normal48_png, AudioslaveAssets::normal48_pngSize, AudioslaveAssets::paused48_png, AudioslaveAssets::paused48_pngSize },
    { 56, AudioslaveAssets::normal56_png, AudioslaveAssets::normal56_pngSize, AudioslaveAssets::paused56_png, AudioslaveAssets::paused56_pngSize },
    { 64, AudioslaveAssets::normal64_png, AudioslaveAssets::normal64_pngSize, AudioslaveAssets::paused64_png, AudioslaveAssets::paused64_pngSize },
    { 128, AudioslaveAssets::normal128_png, AudioslaveAssets::normal128_pngSize, AudioslaveAssets::paused128_png, AudioslaveAssets::paused128_pngSize },
    { 256, AudioslaveAssets::normal256_png, AudioslaveAssets::normal256_pngSize, AudioslaveAssets::paused256_png, AudioslaveAssets::paused256_pngSize },
};

// Smallest frame that is at least `size` (exact for every shell icon size).
const Frame& frameFor (int size)
{
    for (const auto& f : frames)
        if (f.size >= size)
            return f;
    return frames[std::size (frames) - 1];
}
} // namespace

namespace
{
// JUCE's private callback message for the icon (WM_TRAYNOTIFY in
// juce_SystemTrayIcon_windows.cpp).
constexpr UINT juceTrayMessage = WM_USER + 100;
constexpr UINT_PTR subclassId = 0x41534C56;
} // namespace

struct TrayIcon::Native
{
    static LRESULT CALLBACK proc (HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam, UINT_PTR, DWORD_PTR refData)
    {
        auto* self = reinterpret_cast<TrayIcon*> (refData);
        if (message == juceTrayMessage)
        {
            // Version 4: LOWORD(lParam) is the event. None of them is passed
            // on: JUCE's handler only understands version 0 events.
            switch (LOWORD (lParam))
            {
                case NIN_SELECT:
                case NIN_KEYSELECT:
                    dispatch (*self, false);
                    break;
                case WM_CONTEXTMENU:
                    // The shell allows the foreground change for this event;
                    // JUCE dismisses the menus of background processes.
                    ::SetForegroundWindow (hwnd);
                    dispatch (*self, true);
                    break;
                default:
                    break;
            }
            return 0;
        }

        const auto result = ::DefSubclassProc (hwnd, message, wParam, lParam);
        if (message == WM_DISPLAYCHANGE || message == WM_SETTINGCHANGE || message == WM_DPICHANGED)
            if (self->iconSet_ && smallIconSize() != self->iconSize_)
                self->applyIcon(); // new scale: use the frame made for it
        static const UINT taskbarCreated = ::RegisterWindowMessageW (L"TaskbarCreated");
        if (message == taskbarCreated)
            self->useModernProtocol(); // JUCE has just added the icon again
        return result;
    }

    static void dispatch (TrayIcon& icon, bool menu)
    {
        // A modal dialog is open: bring it forward instead (JUCE's behaviour).
        if (icon.isCurrentlyBlockedByAnotherModalComponent())
        {
            if (auto* modal = juce::Component::getCurrentlyModalComponent())
                modal->inputAttemptWhenModal();
            return;
        }
        if (menu)
        {
            if (icon.onMenu)
                icon.onMenu (icon.iconScreenArea());
        }
        else if (icon.onOpen)
        {
            icon.onOpen();
        }
    }
};

TrayIcon::TrayIcon()
{
    applyIcon();
    if (auto hwnd = static_cast<HWND> (getWindowHandle()); hwnd != nullptr
        && ::SetWindowSubclass (hwnd, Native::proc, subclassId, reinterpret_cast<DWORD_PTR> (this)))
    {
        subclassedWindow_ = hwnd;
        useModernProtocol();
    }
}

TrayIcon::~TrayIcon()
{
    // Before JUCE removes the icon and restores its own window procedure.
    if (subclassedWindow_ != nullptr)
        ::RemoveWindowSubclass (static_cast<HWND> (subclassedWindow_), Native::proc, subclassId);
}

void TrayIcon::useModernProtocol()
{
    if (auto* data = static_cast<const NOTIFYICONDATAW*> (getNativeHandle()))
    {
        // A copy: uVersion shares a union with the balloon timeout JUCE uses.
        auto copy = *data;
        copy.uVersion = NOTIFYICON_VERSION_4;
        ::Shell_NotifyIconW (NIM_SETVERSION, &copy);
    }
}

juce::Rectangle<int> TrayIcon::iconScreenArea() const
{
    const auto* data = static_cast<const NOTIFYICONDATAW*> (getNativeHandle());
    if (data == nullptr)
        return {};
    NOTIFYICONIDENTIFIER id {};
    id.cbSize = sizeof (id);
    id.hWnd = data->hWnd;
    id.uID = data->uID;
    RECT r {};
    if (FAILED (::Shell_NotifyIconGetRect (&id, &r)) || r.right <= r.left)
        return {};
    // The shell reports physical pixels.
    return juce::Desktop::getInstance().getDisplays().physicalToLogical (
        juce::Rectangle<int> (r.left, r.top, r.right - r.left, r.bottom - r.top));
}

int TrayIcon::smallIconSize()
{
    // The notification area follows the DPI of the taskbar's monitor, which
    // can differ from the system DPI (another monitor, or the scale changed
    // since logon).
    UINT dpi = 0;
    if (const auto taskbar = ::FindWindowW (L"Shell_TrayWnd", nullptr))
        dpi = ::GetDpiForWindow (taskbar);
    if (dpi == 0)
        dpi = ::GetDpiForSystem();
    return ::GetSystemMetricsForDpi (SM_CXSMICON, dpi);
}

juce::Image TrayIcon::logoImage (bool paused, int size)
{
    const auto& f = frameFor (size);
    return paused ? juce::ImageCache::getFromMemory (f.paused, f.pausedSize)
                  : juce::ImageCache::getFromMemory (f.normal, f.normalSize);
}

void TrayIcon::setPaused (bool paused)
{
    if (paused == paused_ && iconSet_)
        return;
    paused_ = paused;
    applyIcon();
}

void TrayIcon::applyIcon()
{
    const int size = smallIconSize();
    iconSize_ = size;
    if (! iconSet_)
    {
        // JUCE creates the notification icon from its first image.
        const auto image = logoImage (paused_, size);
        setIconImage (image, image);
        // Required tooltip text (fixed).
        setIconTooltip (utf8 (brand::trayTooltipUtf8));
        iconSet_ = true;
    }

    // The shown icon is built by Windows straight from the PNG frame made for
    // this size: straight alpha, no resampling and no premultiplied-alpha
    // round trip through a JUCE bitmap (which darkens the anti-aliased edges
    // of the transparent logo).
    const auto& f = frameFor (size);
    const auto* png = reinterpret_cast<const BYTE*> (paused_ ? f.paused : f.normal);
    const auto bytes = static_cast<DWORD> (paused_ ? f.pausedSize : f.normalSize);
    auto icon = ::CreateIconFromResourceEx (const_cast<PBYTE> (png), bytes, TRUE, 0x00030000, size, size, LR_DEFAULTCOLOR);
    auto* data = static_cast<NOTIFYICONDATAW*> (getNativeHandle());
    if (icon == nullptr || data == nullptr)
    {
        if (icon != nullptr)
            ::DestroyIcon (icon);
        const auto image = logoImage (paused_, size);
        setIconImage (image, image); // fallback: JUCE's conversion
        return;
    }
    // JUCE keeps owning the handle (it re-adds the icon with it when Explorer
    // restarts and destroys it with the icon).
    const auto previous = data->hIcon;
    data->hIcon = icon;
    data->uFlags = NIF_ICON;
    ::Shell_NotifyIconW (NIM_MODIFY, data);
    ::DestroyIcon (previous);
}

} // namespace audioslave
